\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{template/thesis}
\ProcessOptions

\LoadClass[a4paper]{scrreprt} % KOMAscript

% Packages:
\usepackage{graphicx}
\usepackage{lipsum}
\usepackage{textcomp}
\usepackage{mathptmx}
\usepackage{hyperref}
\usepackage{array}
\usepackage[ngerman]{babel, translator}
\usepackage[toc]{glossaries}
\usepackage{color}
\usepackage[table]{xcolor}
\usepackage{listings}
\usepackage{wrapfig}
\usepackage{url}
\usepackage{float}
\usepackage[style=alphabetic]{biblatex}
\usepackage{booktabs}
\usepackage{tabularx}
\usepackage{pdfpages}
\usepackage{fontspec}
\usepackage{titlesec}
\usepackage{ellipsis}
\usepackage[automark, nouppercase]{scrpage2}
\usepackage[some]{background}
\usepackage{multicol}
\usepackage{geometry}
\usepackage{tocstyle}
\usepackage{tikz-uml}
\usepackage{datetime}
\usepackage{pgfgantt}
\usepackage{template/fontawesome}
\usepackage{csquotes}
\usepackage{verbatim}
\usepackage{xspace}

\bibliography{content/indexes/bibliography}
