\NeedsTeXFormat{LaTeX2e}
\ProvidesClass{thesis}
\ProcessOptions

\LoadClass[a4paper]{scrreprt} % KOMAscript

% Packages:
\RequirePackage{graphicx}
\usepackage{lipsum}
\usepackage{textcomp}
\usepackage{mathptmx}
\usepackage{hyperref}
\usepackage{array}
\usepackage{ngerman}
\usepackage{glossaries}
\usepackage{color}
\usepackage[table]{xcolor}
\usepackage{listings}
\usepackage{wrapfig}
\usepackage{url}
\usepackage{float}
\usepackage{natbib}
\usepackage{booktabs}
\usepackage{tabularx}
\usepackage{pdfpages}
\usepackage{fontspec}
\usepackage{titlesec}
\usepackage{ellipsis}
\usepackage[automark, nouppercase]{scrpage2}